### ISSUE TITLE
IO.Thermo Data from fusion lumos

### ISSUE THREAD

**Issue by lonelu** [smith-chem-wisc/MetaMorpheus#1185]
e: System.AggregateException: One or more errors occurred. ---> System.Runtime.InteropServices.COMException: The server threw an exception. (Exception from HRESULT: 0x80010105 (RPC_E_SERVERFAULT))
   at MSFileReaderLib.IXRawfile5.GetNoiseData(Object& pvarNoisePacket, Int32& pnScanNumber)
   at IO.Thermo.ThermoFile.GetMsDataOneBasedScanFromThermoFile(Int32 nScanNumber, IXRawfile5 theConnection, ThermoGlobalParams globalParams, IFilteringParams filterParams)
   at IO.Thermo.ThermoStaticData.LoadAllStaticData(String filePath, IFilteringParams filterParams)
   at TaskLayer.MyFileManager.LoadFile(String origDataFile, Nullable`1 topNpeaks, Nullable`1 minRatio, Boolean trimMs1Peaks, Boolean trimMsMsPeaks) in C:\projects\metamorpheus\TaskLayer\MyFileManager.cs:line 105
   at TaskLayer.GptmdTask.<>c__DisplayClass6_0.<RunSpecific>b__8(Int32 spectraFileIndex) in C:\projects\metamorpheus\TaskLayer\GPTMDTask\GPTMDTask.cs:line 148
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)
   at TaskLayer.GptmdTask.RunSpecific(String OutputFolder, List`1 dbFilenameList, List`1 currentRawFileList, String taskId, FileSpecificParameters[] fileSettingsList) in C:\projects\metamorpheus\TaskLayer\GPTMDTask\GPTMDTask.cs:line 161
   at TaskLayer.MetaMorpheusTask.RunTask(String output_folder, List`1 currentProteinDbFilenameList, List`1 currentRawDataFilepathList, String displayName) in C:\projects\metamorpheus\TaskLayer\MetaMorpheusTask.cs:line 227

**Comment by rmillikin** [comment]
fixed in #1292
