### ISSUE TITLE
Error when importng mzID into Skyline

### ISSUE THREAD

**Issue by yishai99** [smith-chem-wisc/MetaMorpheus#1216]
Hi,
I tried importing an mzID file into Skyline and got this error:
System.IO.IOException: ERROR: Invalid cvParam accession "1002826"
ERROR: 
ERROR: reading file HF1_7314_DSHO_PGI_056_040617_1_240518_180525223915-calib.mzid
ERROR: Invalid cvParam accession "1002826"
ERROR: 
ERROR: reading file HF1_7314_DSHO_PGI_056_060318_1_240518-calib.mzid

   at pwiz.Common.SystemUtil.ProcessRunner.Run(ProcessStartInfo psi, String stdin, IProgressMonitor progress, IProgressStatus& status, TextWriter writer) in c:\proj\skyline_4_1_x64\pwiz_tools\Shared\Common\SystemUtil\ProcessRunner.cs:line 109
   at pwiz.Common.SystemUtil.ProcessRunner.Run(ProcessStartInfo psi, String stdin, IProgressMonitor progress, IProgressStatus& status) in c:\proj\skyline_4_1_x64\pwiz_tools\Shared\Common\SystemUtil\ProcessRunner.cs:line 53
   at pwiz.BiblioSpec.BlibBuild.BuildLibrary(LibraryBuildAction libraryBuildAction, IProgressMonitor progressMonitor, IProgressStatus& status, String[]& ambiguous) in c:\proj\skyline_4_1_x64\pwiz_tools\Shared\BiblioSpec\BlibBuild.cs:line 171
   at pwiz.Skyline.M

Does this mean anything to you? The mzID was created at the 'Task3-SearchTask' step.
I can provide you with the file offline.
Thanks,

Yishai

**Comment by rmillikin** [comment]
I suspect that this problem has to do with some aspects of MetaMorpheus annotation not being recognized in Skyline. I know that we've asked them to add some small things in the past, which they were more than happy to do, and I've successfully imported mzID into Skyline maybe ~1 year ago. We've been adding to our mzID over the past year and some of the new stuff must not be recognized. We can look into this. Also see issue #1125 .

**Comment by yishai99** [comment]
I saw issue 1125. So how do we proceed in enabling import into Skyline?

**Comment by trishorts** [comment]
please see https://skyline.ms/announcements/home/support/thread.view?rowId=35262

**Comment by yishai99** [comment]
Excellent!

**Comment by rmillikin** [comment]
I was able to import a MetaMorpheus .mzID into Skyline Daily, but not Skyline 4.1 (the latest non-beta release). On the .fasta import step it takes a long time though for some reason, I'm not sure if that's a bug in Skyline?

**Comment by rmillikin** [comment]
https://skyline.ms/announcements/home/support/thread.view?rowId=36913
