### ISSUE TITLE
Agilent .d Crash (precursorSpectrum.Size == 0)

### ISSUE THREAD

**Issue by rmillikin** [smith-chem-wisc/MetaMorpheus#1239]
A user has reported a crash with the following error message when converting an Agilent .d file in MSConvert to centroid mzML and running through MetaMorpheus:

```
Could not refine selected m/z and intensity because precursorSpectrum.Size == 0 
System.Collections.ListDictionaryInternal 
   at MassSpectrometry.MsDataScan.RefineSelectedMzAndIntensity(MzSpectrum precursorSpectrum) 
   at TaskLayer.MetaMorpheusTask.<GetMs2Scans>d__42.MoveNext() in C:\projects\metamorpheus\TaskLayer\MetaMorpheusTask.cs:line 123
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source) 
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext() 
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source) 
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source) 
   at TaskLayer.CalibrationTask.GetDataAcquisitionResults(MsDataFile myMsDataFile, String currentDataFile, List`1 variableModifications, List`1 fixedModifications, List`1 proteinList, String taskId, CommonParameters combinedParameters, Tolerance initPrecTol, Tolerance initProdTol) in C:\projects\metamorpheus\TaskLayer\CalibrationTask\CalibrationTask.cs:line 317
   at TaskLayer.CalibrationTask.RunSpecific(String OutputFolder, List`1 dbFilenameList, List`1 currentRawFileList, String taskId, FileSpecificParameters[] fileSettingsList) in C:\projects\metamorpheus\TaskLayer\CalibrationTask\CalibrationTask.cs:line 122
   at TaskLayer.MetaMorpheusTask.RunTask(String output_folder, List`1 currentProteinDbFilenameList, List`1 currentRawDataFilepathList, String displayName) in C:\projects\metamorpheus\TaskLayer\MetaMorpheusTask.cs:line 258
   at TaskLayer.EverythingRunnerEngine.Run() in C:\projects\metamorpheus\TaskLayer\EverythingRunnerEngine.cs:line 97 
   at System.Threading.Tasks.Task.Execute() 
MassSpectrometry 
```

I'm guessing that the precursor scan has no peaks, and MM crashes trying to deconvolute the isolation window. Or at least the isolation window has no peaks in it. Or the isolation window is messed up in the mzML.

**Comment by rmillikin** [comment]
crash likely fixed in #1243 with appropriate error message. unable to test directly because of data confidentiality. will reopen this issue if it ends up not being a valid fix.
