### ISSUE TITLE
XL search crashed...

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#1727]
Hi,
I've searched multiple files using XL search and got the following error message :)

Thanks!
D.

MetaMorpheus: version 0.0.301
Data files were processed on a VMware, Inc. VMware Virtual Platform computer using Windows version 6.1.7601.65536 with a 64-Bit processor and 26 cores operating at 2.7GHz and 128GB installed RAM.
.NET Framework Version: 4.7 or laterThermo MSFileReader Fileio DLL		Version: 3.1
Thermo MSFileReader Fregistry DLL		Version: 2.0
Thermo MSFileReader Rawfile Com Interface		Version: 3.1.9.0

e: System.Runtime.InteropServices.COMException (0x80010105): The server threw an exception. (Exception from HRESULT: 0x80010105 (RPC_E_SERVERFAULT))
   at MSFileReaderLib.IXRawfile5.GetLabelData(Object& pvarLabels, Object& pvarFlags, Int32& pnScanNumber)
   at IO.Thermo.ThermoStaticData.GetMsDataOneBasedScanFromThermoFile(IXRawfile5 theConnection, Int32 nScanNumber, ThermoGlobalParams globalParams, IFilteringParams filterParams)
   at IO.Thermo.ThermoStaticData.LoadAllStaticData(String filePath, IFilteringParams filterParams)
   at TaskLayer.MyFileManager.LoadFile(String origDataFile, CommonParameters commonParameters) in C:\projects\metamorpheus\TaskLayer\MyFileManager.cs:line 104
   at TaskLayer.XLSearchTask.RunSpecific(String OutputFolder, List`1 dbFilenameList, List`1 currentRawFileList, String taskId, FileSpecificParameters[] fileSettingsList) in C:\projects\metamorpheus\TaskLayer\XLSearchTask\XLSearchTask.cs:line 84
   at TaskLayer.MetaMorpheusTask.RunTask(String output_folder, List`1 currentProteinDbFilenameList, List`1 currentRawDataFilepathList, String displayName) in C:\projects\metamorpheus\TaskLayer\MetaMorpheusTask.cs:line 389e.Message: The server threw an exception. (Exception from HRESULT: 0x80010105 (RPC_E_SERVERFAULT))e.InnerException: e.Source: Thermoe.StackTrace:    at MSFileReaderLib.IXRawfile5.GetLabelData(Object& pvarLabels, Object& pvarFlags, Int32& pnScanNumber)
   at IO.Thermo.ThermoStaticData.GetMsDataOneBasedScanFromThermoFile(IXRawfile5 theConnection, Int32 nScanNumber, ThermoGlobalParams globalParams, IFilteringParams filterParams)
   at IO.Thermo.ThermoStaticData.LoadAllStaticData(String filePath, IFilteringParams filterParams)
   at TaskLayer.MyFileManager.LoadFile(String origDataFile, CommonParameters commonParameters) in C:\projects\metamorpheus\TaskLayer\MyFileManager.cs:line 104
   at TaskLayer.XLSearchTask.RunSpecific(String OutputFolder, List`1 dbFilenameList, List`1 currentRawFileList, String taskId, FileSpecificParameters[] fileSettingsList) in C:\projects\metamorpheus\TaskLayer\XLSearchTask\XLSearchTask.cs:line 84
   at TaskLayer.MetaMorpheusTask.RunTask(String output_folder, List`1 currentProteinDbFilenameList, List`1 currentRawDataFilepathList, String displayName) in C:\projects\metamorpheus\TaskLayer\MetaMorpheusTask.cs:line 389e.TargetSite: Void GetLabelData(System.Object ByRef, System.Object ByRef, Int32 ByRef)

**Comment by trishorts** [comment]
Thanks. We'll have a look.

**Comment by rmillikin** [comment]
This seems like a crash in Thermo's code (MSFileReader). I'm not exactly sure what this error message means either. Can you try converting your data to .mzML and run it through?

**Comment by rmillikin** [comment]
The next version should hopefully obviate this crash, we've switched over to RawFileReader...

**Comment by Dmorgen** [comment]
Will try, thanks!

**Comment by rmillikin** [comment]
Have you had a chance to run this data through 0.0.302? This search should hopefully work with the new version, which uses RawFileReader instead of MSFileReader.

**Comment by Dmorgen** [comment]
Hi,

Sorry for not getting back to you, I’m on constant flights until 5th of Nov… didn’t have a chance (but really need to!).

D.

**Comment by rmillikin** [comment]
I'm closing this for now because it seems this is likely fixed (?) but if it's not, please reopen
