### ISSUE TITLE
Index search crashes when reading index if two proteins have the same accession

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#1852]
Hi,

please see the following crash report:
MetaMorpheus: version 0.0.304
Data files were processed on a VMware, Inc. VMware7,1 computer using Windows version 6.2.9200.0 with a 64-Bit processor and 32 cores operating at 2.1GHz and 128GB installed RAM.
.NET Framework Version: 4.7 or laterC:\Program Files\Thermo\MSFileReader\Fileio_x64.dll MISSING\nC:\Program Files\Thermo\MSFileReader\fregistry_x64.dll MISSING\nC:\Program Files\Thermo\MSFileReader\XRawfile2_x64.dll MISSING\n
e: MzLibUtil.MzLibException: A crash occured in FlashLFQ during the intensity normalization process:
Sequence contains no elements
   at FlashLFQ.FlashLfqEngine.Run()
   at TaskLayer.PostSearchAnalysisTask.QuantificationAnalysis() in C:\projects\metamorpheus\TaskLayer\SearchTask\PostSearchAnalysisTask.cs:line 455
   at TaskLayer.PostSearchAnalysisTask.Run() in C:\projects\metamorpheus\TaskLayer\SearchTask\PostSearchAnalysisTask.cs:line 66
   at TaskLayer.SearchTask.RunSpecific(String OutputFolder, List`1 dbFilenameList, List`1 currentRawFileList, String taskId, FileSpecificParameters[] fileSettingsList) in C:\projects\metamorpheus\TaskLayer\SearchTask\SearchTask.cs:line 381
   at TaskLayer.MetaMorpheusTask.RunTask(String output_folder, List`1 currentProteinDbFilenameList, List`1 currentRawDataFilepathList, String displayName) in C:\projects\metamorpheus\TaskLayer\MetaMorpheusTask.cs:line 430e.Message: A crash occured in FlashLFQ during the intensity normalization process:
Sequence contains no elementse.InnerException: e.Source: FlashLFQe.StackTrace:    at FlashLFQ.FlashLfqEngine.Run()
   at TaskLayer.PostSearchAnalysisTask.QuantificationAnalysis() in C:\projects\metamorpheus\TaskLayer\SearchTask\PostSearchAnalysisTask.cs:line 455
   at TaskLayer.PostSearchAnalysisTask.Run() in C:\projects\metamorpheus\TaskLayer\SearchTask\PostSearchAnalysisTask.cs:line 66
   at TaskLayer.SearchTask.RunSpecific(String OutputFolder, List`1 dbFilenameList, List`1 currentRawFileList, String taskId, FileSpecificParameters[] fileSettingsList) in C:\projects\metamorpheus\TaskLayer\SearchTask\SearchTask.cs:line 381
   at TaskLayer.MetaMorpheusTask.RunTask(String output_folder, List`1 currentProteinDbFilenameList, List`1 currentRawDataFilepathList, String displayName) in C:\projects\metamorpheus\TaskLayer\MetaMorpheusTask.cs:line 430e.TargetSite: FlashLFQ.FlashLfqResults Run()

thanks!
D.

**Comment by Dmorgen** [comment]
and another crash on a related search using semi-specific search parameters:
MetaMorpheus: version 0.0.304
Data files were processed on a VMware, Inc. VMware7,1 computer using Windows version 6.2.9200.0 with a 64-Bit processor and 32 cores operating at 2.1GHz and 128GB installed RAM.
.NET Framework Version: 4.7 or laterC:\Program Files\Thermo\MSFileReader\Fileio_x64.dll MISSING\nC:\Program Files\Thermo\MSFileReader\fregistry_x64.dll MISSING\nC:\Program Files\Thermo\MSFileReader\XRawfile2_x64.dll MISSING\n
e: EngineLayer.MetaMorpheusException: The protein database contained multiple proteins with accession P19013 ! This is not allowed for index-based searches (modern, non-specific, crosslink searches)
   at TaskLayer.MetaMorpheusTask.ReadPeptideIndex(String peptideIndexFileName, List`1 allKnownProteins) in C:\projects\metamorpheus\TaskLayer\MetaMorpheusTask.cs:line 682
   at TaskLayer.MetaMorpheusTask.GenerateIndexes(IndexingEngine indexEngine, List`1 dbFilenameList, List`1& peptideIndex, List`1[]& fragmentIndex, List`1[]& precursorIndex, List`1 allKnownProteins, String taskId) in C:\projects\metamorpheus\TaskLayer\MetaMorpheusTask.cs:line 819
   at TaskLayer.SearchTask.RunSpecific(String OutputFolder, List`1 dbFilenameList, List`1 currentRawFileList, String taskId, FileSpecificParameters[] fileSettingsList) in C:\projects\metamorpheus\TaskLayer\SearchTask\SearchTask.cs:line 303
   at TaskLayer.MetaMorpheusTask.RunTask(String output_folder, List`1 currentProteinDbFilenameList, List`1 currentRawDataFilepathList, String displayName) in C:\projects\metamorpheus\TaskLayer\MetaMorpheusTask.cs:line 430e.Message: The protein database contained multiple proteins with accession P19013 ! This is not allowed for index-based searches (modern, non-specific, crosslink searches)e.InnerException: e.Source: TaskLayere.StackTrace:    at TaskLayer.MetaMorpheusTask.ReadPeptideIndex(String peptideIndexFileName, List`1 allKnownProteins) in C:\projects\metamorpheus\TaskLayer\MetaMorpheusTask.cs:line 682
   at TaskLayer.MetaMorpheusTask.GenerateIndexes(IndexingEngine indexEngine, List`1 dbFilenameList, List`1& peptideIndex, List`1[]& fragmentIndex, List`1[]& precursorIndex, List`1 allKnownProteins, String taskId) in C:\projects\metamorpheus\TaskLayer\MetaMorpheusTask.cs:line 819
   at TaskLayer.SearchTask.RunSpecific(String OutputFolder, List`1 dbFilenameList, List`1 currentRawFileList, String taskId, FileSpecificParameters[] fileSettingsList) in C:\projects\metamorpheus\TaskLayer\SearchTask\SearchTask.cs:line 303
   at TaskLayer.MetaMorpheusTask.RunTask(String output_folder, List`1 currentProteinDbFilenameList, List`1 currentRawDataFilepathList, String displayName) in C:\projects\metamorpheus\TaskLayer\MetaMorpheusTask.cs:line 430e.TargetSite: System.Collections.Generic.List`1[Proteomics.ProteolyticDigestion.PeptideWithSetModifications] ReadPeptideIndex(System.String, System.Collections.Generic.List`1[Proteomics.Protein])

**Comment by zrolfs** [comment]
I can speak to the second one. It sounds looks like your protein database contains to entries for the accession "P19013". You need to delete the duplicate or rename it if it's a different sequence. Something like "P19013_2".

**Comment by zrolfs** [comment]
We can also fix the database for you if you send it to us.

**Comment by Dmorgen** [comment]
The search is from the downloaded swissprot XML DB, and after the GPTMD. I can send you a a link to the folder so you can see exactly what it has as input

**Comment by zrolfs** [comment]
Yes please. It'd be helpful to see the database from both before and after GPTMD so we can isolate the issue.

**Comment by zrolfs** [comment]
It looks like the indexed search throws an error because a human protein (keratin) is present in both the contaminant and target databases.
I propose two options, of which I'm leaning the first one:
1. We remove the contaminant and keep the target. If there are two targets with the same accession, still throw an error.
2. We handle this by reassigning the accession number rather than throwing an exception. In this example, the two accessions become "P19013_1" and "P19013_2". You could also do "P19013_T" and "P19013_C" and still throw an exception if there's two targets with the same accession.

@rmillikin thoughts?

**Comment by Dmorgen** [comment]
If I may, I wouldn’t do 1, since searches with other species may be hurt.

D.

**Comment by zrolfs** [comment]
> If I may, I wouldn’t do 1, since searches with other species may be hurt. 

I don't quite understand, can you elaborate? The first proposal is that if an accession is present in both contaminant and target databases, then the contaminant sequence is removed. This would only affect other species if they were also in the contaminant database. Homologous proteins across species have different accession numbers.

**Comment by zrolfs** [comment]
Weird. This exception is only thrown when reading an index. If you're running it for the first time, it works fine.

**Comment by Dmorgen** [comment]
Ah, ok. Now I get it…

**Comment by rmillikin** [comment]
I think to solve the second one, as @zrolfs implied, you will just need to delete your old index and have MetaMorpheus rebuild it. The index is probably built from an older version of MetaMorpheus that contained a bug, and newer versions have the bug fixed. So you will just need to delete the old index and have the new version of MM rebuild the index. If you're not sure what I mean I can elaborate.

For the quantification crash, I think I will need your entire dataset unfortunately. Normalization crashes are hard to identify in isolation. Can you send your data to me?

Thanks!

**Comment by zrolfs** [comment]
@rmillikin creating a new index is a short term fix. This isn't a version issue and it will crash again when it tries to read the new index. Are you okay with the fix I proposed?

**Comment by Dmorgen** [comment]
I’ve figured out what was the quantification problem – there was one of the samples accidentally set as tech replicate 2, without any replicate 1…

**Comment by rmillikin** [comment]
@zrolfs ah ok I misunderstood. This is related to the discussion with @blfrey and @trishorts about what to do with proteins that appear in both the contaminant and target lists. I think we need some kind of user-facing setting about what to do with these conflicts (keep target, keep contaminant, keep both and rename them)

@Dmorgen ok thanks. MM is supposed to prevent that from happening, at least in the GUI. I think that can definetly occur if the experimental design is created outside of the GUI though (e.g., in Excel). If you made it with the GUI I need to fix something still

**Comment by Dmorgen** [comment]
It happened using the GUI.

D.

**Comment by blfrey** [comment]
I agree with @rmillikin that it would be best to have a user-facing setting asking what to do with assigning a protein that appears in both T and C databases.

**Comment by zrolfs** [comment]
Opinions on default behavior? Remove contaminants? Remove targets? Rename them and keep both? Cases can be made for all of them. I'm leaning remove contaminants.

I'm going to also implement code for shared peptides (not just proteins). Not sure how to handle the case where both are kept... just call it a contaminant but still report the target and contaminant? I think that's what we do right now.

**Comment by blfrey** [comment]
I also would lean toward "remove contaminants" as the default

**Comment by rmillikin** [comment]
fixed in #1854
