### ISSUE TITLE
Crash at end of run when using open mass diff acceptor in search task

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1908]
MetaMorpheus: version 0.0.305
Data files were processed on a computer running Microsoft Windows 10.0.18362 with a 64-bit AMD Ryzen 7 3700X 8-Core Processor              processor with 16 threads and 0GB installed RAM.
.NET version: .NET Core 3.1.2
e: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'toExclusive')
   at System.Collections.Concurrent.Partitioner.Create(Int32 fromInclusive, Int32 toExclusive)
   at EngineLayer.Localization.LocalizationEngine.RunSpecific() in C:\projects\metamorpheus\EngineLayer\Localization\LocalizationEngine.cs:line 38
   at EngineLayer.MetaMorpheusEngine.Run() in C:\projects\metamorpheus\EngineLayer\MetaMorpheusEngine.cs:line 175
   at TaskLayer.PostSearchAnalysisTask.DoMassDifferenceLocalizationAnalysis() in C:\projects\metamorpheus\TaskLayer\SearchTask\PostSearchAnalysisTask.cs:line 159
   at TaskLayer.PostSearchAnalysisTask.Run() in C:\projects\metamorpheus\TaskLayer\SearchTask\PostSearchAnalysisTask.cs:line 64
   at TaskLayer.SearchTask.RunSpecific(String OutputFolder, List`1 dbFilenameList, List`1 currentRawFileList, String taskId, FileSpecificParameters[] fileSettingsList) in C:\projects\metamorpheus\TaskLayer\SearchTask\SearchTask.cs:line 382
   at TaskLayer.MetaMorpheusTask.RunTask(String output_folder, List`1 currentProteinDbFilenameList, List`1 currentRawDataFilepathList, String displayName) in C:\projects\metamorpheus\TaskLayer\MetaMorpheusTask.cs:line 446e.Message: Specified argument was out of the range of valid values. (Parameter 'toExclusive')e.InnerException: e.Source: System.Collections.Concurrente.StackTrace:    at System.Collections.Concurrent.Partitioner.Create(Int32 fromInclusive, Int32 toExclusive)
   at EngineLayer.Localization.LocalizationEngine.RunSpecific() in C:\projects\metamorpheus\EngineLayer\Localization\LocalizationEngine.cs:line 38
   at EngineLayer.MetaMorpheusEngine.Run() in C:\projects\metamorpheus\EngineLayer\MetaMorpheusEngine.cs:line 175
   at TaskLayer.PostSearchAnalysisTask.DoMassDifferenceLocalizationAnalysis() in C:\projects\metamorpheus\TaskLayer\SearchTask\PostSearchAnalysisTask.cs:line 159
   at TaskLayer.PostSearchAnalysisTask.Run() in C:\projects\metamorpheus\TaskLayer\SearchTask\PostSearchAnalysisTask.cs:line 64
   at TaskLayer.SearchTask.RunSpecific(String OutputFolder, List`1 dbFilenameList, List`1 currentRawFileList, String taskId, FileSpecificParameters[] fileSettingsList) in C:\projects\metamorpheus\TaskLayer\SearchTask\SearchTask.cs:line 382
   at TaskLayer.MetaMorpheusTask.RunTask(String output_folder, List`1 currentProteinDbFilenameList, List`1 currentRawDataFilepathList, String displayName) in C:\projects\metamorpheus\TaskLayer\MetaMorpheusTask.cs:line 446e.TargetSite: System.Collections.Concurrent.OrderablePartitioner`1[System.Tuple`2[System.Int32,System.Int32]] Create(Int32, Int32)

**Comment by rmillikin** [comment]
quick guess but it could be that there were no mods observed <1% FDR. 

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'toExclusive')
at System.Collections.Concurrent.Partitioner.Create(Int32 fromInclusive, Int32 toExclusive)
```

this error usually shows up when a parallel loop tries to partition an empty list. the localization engine tries to localize mods <1% FDR. combined w/ above evidence it seems that list of PSMs is empty.
