### ISSUE TITLE
System.OutOfMemoryException

### ISSUE THREAD

**Issue by rpm78** [smith-chem-wisc/MetaMorpheus#1951]
Hi,

I came across the following issue while trying to run MetaMorpheus.

While running version 0.309, a Calibration task consistently failed with a System.OutofMemoryException.

This occurred with MetaMorpheus running on the following platforms:

| Platform |      Chip      | Memory | MetaMorpheus | System                                                             |
|:--------:|:--------------:|:------:|:------------:|--------------------------------------------------------------------|
|     A    | core-i7 7700HQ |  32 GB |      GUI     | Win10 guest in VirtualBox on linux mint 19 (ubuntu 18.04 LTS) host |
|     B    |    Xeon 8000   |  32 GB |      GUI     | Win Server on AWS EC2 C5d.4xlarge instance                         |
|     C    | core-i7 7700HQ |  32 GB |      CMD     | docker on linux mint 19 (ubuntu 18.04 LTS) (same hardware as A)    |

Both raw files and mzML files threw the exception.  
The initial files were from a duplex NeuCode SILAC experiment run on a Thermo Fusion Lumos.
I also reproduced the error with the test files provided on github.io (downloaded from Box).

A search task did complete successfully on platform A and C (B wasn't tried).  

When Metamorpheus was rolled back to version 0.308 the calibration task ran successfully (on C; A and B weren't tried).

Here is the summary returned in the results.txt file using version 0.309 on C:
```
MetaMorpheus: version 0.0.309
Data files were processed on a computer running Linux 4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 with a 64-bit Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz processor with 8 threads and 32GB installed RAM.
.NET version: .NET Core 3.1.7
e: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
   at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
   at System.Text.Encoding.GetString(Byte[] bytes)
   at IO.MzML.MzmlMethods.CreateAndWriteMyMzmlWithCalibratedSpectra(MsDataFile myMsDataFile, String outputFile, Boolean writeIndexed)
   at TaskLayer.CalibrationTask.RunSpecific(String OutputFolder, List`1 dbFilenameList, List`1 currentRawFileList, String taskId, FileSpecificParameters[] fileSettingsList)
   at TaskLayer.MetaMorpheusTask.RunTask(String output_folder, List`1 currentProteinDbFilenameList, List`1 currentRawDataFilepathList, String displayName)e.Message: Exception of type 'System.OutOfMemoryException' was thrown.e.InnerException: e.Source: System.Private.CoreLibe.StackTrace:    at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
   at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
   at System.Text.Encoding.GetString(Byte[] bytes)
   at IO.MzML.MzmlMethods.CreateAndWriteMyMzmlWithCalibratedSpectra(MsDataFile myMsDataFile, String outputFile, Boolean writeIndexed)
   at TaskLayer.CalibrationTask.RunSpecific(String OutputFolder, List`1 dbFilenameList, List`1 currentRawFileList, String taskId, FileSpecificParameters[] fileSettingsList)
   at TaskLayer.MetaMorpheusTask.RunTask(String output_folder, List`1 currentProteinDbFilenameList, List`1 currentRawDataFilepathList, String displayName)e.TargetSite: System.String CreateStringFromEncoding(Byte*, Int32, System.Text.Encoding)
```

**Comment by trishorts** [comment]
thanks for this message. we've seen this three or four times now. we're looking into it and will respond as soon as we can.

**Comment by trishorts** [comment]
we tracked down and found the source of the problem. it occurs when writing indexed mzml files after calibration. this bug was introduced in a recent version. For now we are reverting the change. Please update your copy of metamorpheus to version 310. that code will work until we can fix this bug.

**Comment by rpm78** [comment]
Great, thanks for letting me know.

**Comment by trishorts** [comment]
please let me know if you are able to successfully get version 310 (it should show up as an automatic update). it's already available.

**Comment by rpm78** [comment]
The calibration task with the same spectral files and setups (A and C) worked for me with version 310.
Happy to see closed unless you want to keep it open.
