### ISSUE TITLE
Run failed, Exception: The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by MKoesters** [smith-chem-wisc/MetaMorpheus#1954]
Hi,

I'm running the Commandline of MetaMorpheus v0.0.308 on CentOS 7 and I'm getting the following error

```
Run failed, Exception: The given key '20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_25-calib' was not present in the dictionary.
```

However If I check my ExperimentalDesign.tsv like the following
```
➜  grep ssb_25 ExperimentalDesign.tsv
20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_25-calib    SSB1_KO    1    1    3
```

I find a line with the correct name.

Here is the output of results.txt in the Task5SearchTask Folder:

```
MetaMorpheus: version 0.0.308
Data files were processed on a computer running Linux 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 with a 64-bit Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz processor with 40 threads and 263GB installed RAM.
.NET version: .NET Core 3.1.7
e: System.Collections.Generic.KeyNotFoundException: The given key '20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_25-calib' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TaskLayer.PostSearchAnalysisTask.QuantificationAnalysis()
   at TaskLayer.PostSearchAnalysisTask.Run()
   at TaskLayer.SearchTask.RunSpecific(String OutputFolder, List`1 dbFilenameList, List`1 currentRawFileList, String taskId, FileSpecificParameters[] fileSettingsList)
   at TaskLayer.MetaMorpheusTask.RunTask(String output_folder, List`1 currentProteinDbFilenameList, List`1 currentRawDataFilepathList, String displayName)e.Message: The given key '20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_25-calib' was not present in the dictionary.e.InnerException: e.Source: System.Private.CoreLibe.StackTrace:    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TaskLayer.PostSearchAnalysisTask.QuantificationAnalysis()
   at TaskLayer.PostSearchAnalysisTask.Run()
   at TaskLayer.SearchTask.RunSpecific(String OutputFolder, List`1 dbFilenameList, List`1 currentRawFileList, String taskId, FileSpecificParameters[] fileSettingsList)
   at TaskLayer.MetaMorpheusTask.RunTask(String output_folder, List`1 currentProteinDbFilenameList, List`1 currentRawDataFilepathList, String displayName)e.TargetSite: Void ThrowKeyNotFoundException[T](T)%
```

Here is the full ExperimentalDesign.tsv which I put in the folder with all the mzML files

[ExperimentalDesign.zip](https://github.com/smith-chem-wisc/MetaMorpheus/files/5232858/ExperimentalDesign.zip)

```
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_01.mgf
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_01.mgf.u.json
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_01.mzML
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_01.raw
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_02.mzML
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_02.raw
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_03.mzML
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_03.raw
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_04.mzML
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_04.raw
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_05.mzML
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_05.raw
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_06.mzML
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_06.raw
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_07.mzML
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_07.raw
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_08.mzML
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_08.raw
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_09.mzML
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_09.raw
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_10.mzML
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_10.raw
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_11.mzML
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_11.raw
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_12.mzML
├── 20131106_exp0583_Yeast-inclusionbodies_Ingel_ssb_12.raw
├── ExperimentalDesign.tsv
└── ExperimentalDesign.zip
```

I also tried to remove the `-calib` part, but it did not help.

I'm happy about anything which helps me solve this problem.

**Comment by trishorts** [comment]
can you post the .toml file

**Comment by rmillikin** [comment]
I'm not 100% sure if this will fix it, but when I take a look at the ExperimentalDesign.tsv file you linked, that file (along with a few others) are delimited with spaces instead of tabs. MetaMorpheus is expecting tabs to delimit the data in the different columns.

![Untitled](https://user-images.githubusercontent.com/24705713/93366287-8dc6c280-f810-11ea-95ad-d0d9d4ba6ad0.png)

For example lines until row 72 are delimited w/ spaces, lines 73 onward are incorrectly delimited with spaces. If you fix that, does the run proceed as expected?

**Comment by MKoesters** [comment]
Ah, damn, I had issues with tabs and spaces in Emacs but I thought I got that fixed ...
Sry, I'll check my tsv and make sure everything is correctly formatted and then either close the issue or follow up with my toml files.
Thanks a lot!
