### ISSUE TITLE
error in calibration step run

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/MetaMorpheus#2030]
please see the attached:

thanks!
David.

MetaMorpheus: version 0.0.315
Data files were processed on a computer running Microsoft Windows 10.0.17763 with a 64-bit Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz processor with 32 threads and 128GB installed RAM.
.NET version: .NET Core 3.1.3
e: System.ArgumentException: The output byte buffer is too small to contain the encoded data, encoding 'Unicode (UTF-8)' fallback 'System.Text.EncoderReplacementFallback'. (Parameter 'bytes')
   at System.Text.Encoding.ThrowBytesOverflow()
   at System.Text.Encoding.ThrowBytesOverflow(EncoderNLS encoder, Boolean nothingEncoded)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar)
   at System.Text.UTF8Encoding.GetBytes(String s, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex)
   at IO.MzML.MzmlMethods.GetSHA1Hash(String filePath)
   at IO.MzML.MzmlMethods.CreateAndWriteMyMzmlWithCalibratedSpectra(MsDataFile myMsDataFile, String outputFile, Boolean writeIndexed)
   at TaskLayer.CalibrationTask.RunSpecific(String OutputFolder, List`1 dbFilenameList, List`1 currentRawFileList, String taskId, FileSpecificParameters[] fileSettingsList) in C:\projects\metamorpheus\TaskLayer\CalibrationTask\CalibrationTask.cs:line 180
   at TaskLayer.MetaMorpheusTask.RunTask(String output_folder, List`1 currentProteinDbFilenameList, List`1 currentRawDataFilepathList, String displayName) in C:\projects\metamorpheus\TaskLayer\MetaMorpheusTask.cs:line 451e.Message: The output byte buffer is too small to contain the encoded data, encoding 'Unicode (UTF-8)' fallback 'System.Text.EncoderReplacementFallback'. (Parameter 'bytes')e.InnerException: e.Source: System.Private.CoreLibe.StackTrace:    at System.Text.Encoding.ThrowBytesOverflow()
   at System.Text.Encoding.ThrowBytesOverflow(EncoderNLS encoder, Boolean nothingEncoded)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar)
   at System.Text.UTF8Encoding.GetBytes(String s, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex)
   at IO.MzML.MzmlMethods.GetSHA1Hash(String filePath)
   at IO.MzML.MzmlMethods.CreateAndWriteMyMzmlWithCalibratedSpectra(MsDataFile myMsDataFile, String outputFile, Boolean writeIndexed)
   at TaskLayer.CalibrationTask.RunSpecific(String OutputFolder, List`1 dbFilenameList, List`1 currentRawFileList, String taskId, FileSpecificParameters[] fileSettingsList) in C:\projects\metamorpheus\TaskLayer\CalibrationTask\CalibrationTask.cs:line 180
   at TaskLayer.MetaMorpheusTask.RunTask(String output_folder, List`1 currentProteinDbFilenameList, List`1 currentRawDataFilepathList, String displayName) in C:\projects\metamorpheus\TaskLayer\MetaMorpheusTask.cs:line 451e.TargetSite: Void ThrowBytesOverflow()

**Comment by trishorts** [comment]
Thanks David. I have some ideas about this. Is it possible that one of your files contains very few PSMs and it couldn't be calibrated? Maybe you could do a quick search on the same set and skip calibration to see which one might be the offending file?

**Comment by Dmorgen** [comment]
Sure, although analysis with MaxQuant doesn’t show low ID number in any of the samples.
I will prepare a download link.

D.

**Comment by trishorts** [comment]
thanks david. we'll figure this out,

**Comment by trishorts** [comment]
I believe that I have found and corrected the error. I'm waiting for review, merge and release. Please keep your eye out for a new release prompt.

**Comment by rmillikin** [comment]
This error should only occur with writing indexed .mzML - if you disable this option in the Calibration task output options, the calibrated files should write fine, albeit not indexed.

**Comment by trishorts** [comment]
Changes to fix this bug have been submitted. Automated testing will be performed overnight. If the tests pass, we will make a new release in the morning (USA, central time).

If you need a version faster, I can get you a pre-release version.

**Comment by trishorts** [comment]
the new version of MM with a fix has been released. please download version 3.16 and let us know if that solves the problem.

**Comment by Dmorgen** [comment]
Thanks!
