### ISSUE TITLE
Crash - Index was outside the bounds of the array - XLSearchTask

### ISSUE THREAD

**Issue by xLinkKnight** [smith-chem-wisc/MetaMorpheus#2366]
Running the latest release of MetaMorpheus (1.0.5).

Crash when attempting to perform a crosslink search when using MGF files. MGF files were generated by MSConvert from Bruker SCP raw files.

Error: ```Run failed, Exception: Index was outside the bounds of the array.```

**The results file contains the following:**

```MetaMorpheus: version 1.0.5
Data files were processed on a computer running Microsoft Windows 10.0.22631 with a 64-bit AMD EPYC 9754 128-Core Processor                processor with 64 threads and 768GB installed RAM.
.NET version: .NET 6.0.30
e: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Readers.Mgf.GetNextMsDataOneBasedScanFromConnection(StreamReader sr, HashSet`1 scanNumbersAlreadyObserved, IFilteringParams filterParams, Nullable`1 alreadyKnownScanNumber)
   at Readers.Mgf.LoadAllStaticData(FilteringParams filterParams, Int32 maxThreads)
   at TaskLayer.MyFileManager.LoadFile(String origDataFile, CommonParameters commonParameters) in C:\projects\metamorpheus\MetaMorpheus\TaskLayer\MyFileManager.cs:line 53
   at TaskLayer.XLSearchTask.RunSpecific(String OutputFolder, List`1 dbFilenameList, List`1 currentRawFileList, String taskId, FileSpecificParameters[] fileSettingsList) in C:\projects\metamorpheus\MetaMorpheus\TaskLayer\XLSearchTask\XLSearchTask.cs:line 96
   at TaskLayer.MetaMorpheusTask.RunTask(String output_folder, List`1 currentProteinDbFilenameList, List`1 currentRawDataFilepathList, String displayName) in C:\projects\metamorpheus\MetaMorpheus\TaskLayer\MetaMorpheusTask.cs:line 509e.Message: Index was outside the bounds of the array.e.InnerException: e.Source: Readerse.StackTrace:    at Readers.Mgf.GetNextMsDataOneBasedScanFromConnection(StreamReader sr, HashSet`1 scanNumbersAlreadyObserved, IFilteringParams filterParams, Nullable`1 alreadyKnownScanNumber)
   at Readers.Mgf.LoadAllStaticData(FilteringParams filterParams, Int32 maxThreads)
   at TaskLayer.MyFileManager.LoadFile(String origDataFile, CommonParameters commonParameters) in C:\projects\metamorpheus\MetaMorpheus\TaskLayer\MyFileManager.cs:line 53
   at TaskLayer.XLSearchTask.RunSpecific(String OutputFolder, List`1 dbFilenameList, List`1 currentRawFileList, String taskId, FileSpecificParameters[] fileSettingsList) in C:\projects\metamorpheus\MetaMorpheus\TaskLayer\XLSearchTask\XLSearchTask.cs:line 96
   at TaskLayer.MetaMorpheusTask.RunTask(String output_folder, List`1 currentProteinDbFilenameList, List`1 currentRawDataFilepathList, String displayName) in C:\projects\metamorpheus\MetaMorpheus\TaskLayer\MetaMorpheusTask.cs:line 509e.TargetSite: MassSpectrometry.MsDataScan GetNextMsDataOneBasedScanFromConnection(System.IO.StreamReader, System.Collections.Generic.HashSet`1[System.Int32], MassSpectrometry.IFilteringParams, System.Nullable`1[System.Int32])
```

**XL-Task.toml:**
```
TaskType = "XLSearch"

[XlSearchParameters]
DecoyType = "Reverse"
CrosslinkSearchTopNum = 50
CrosslinkAtCleavageSite = false
WritePepXml = true
WriteOutputForPercolator = false
WriteSpectralLibrary = false
XlQuench_H2O = true
XlQuench_Tris = false
XlQuench_NH2 = true

[XlSearchParameters.Crosslinker]
CrosslinkerModSites = "K"
CrosslinkerModSites2 = "K"
CrosslinkerName = "DSSO"
Cleavable = true
CleaveDissociationTypes = ["CID", "HCD"]
TotalMass = 158.0038
CleaveMassShort = 54.01056
CleaveMassLong = 85.982635
LoopMass = 158.0038
DeadendMassH2O = 176.0143
DeadendMassNH2 = 175.0303
DeadendMassTris = 279.0777

[CommonParameters]
TaskDescriptor = "ProteinX_DSSO"
MaxThreadsToUsePerFile = 63
ListOfModsFixed = "Common Fixed\tCarbamidomethyl on C\t\tCommon Fixed\tCarbamidomethyl on U"
ListOfModsVariable = "Common Variable\tOxidation on M"
DoPrecursorDeconvolution = true
UseProvidedPrecursorInfo = true
DeconvolutionIntensityRatio = 3.0
DeconvolutionMaxAssumedChargeState = 12
DeconvolutionMassTolerance = "±4.0000 PPM"
TotalPartitions = 1
ProductMassTolerance = "±20.0000 PPM"
PrecursorMassTolerance = "±20.0000 PPM"
AddCompIons = false
QValueThreshold = 0.01
PepQValueThreshold = 1.0
ScoreCutoff = 3.0
ReportAllAmbiguity = true
NumberOfPeaksToKeepPerWindow = 200
MinimumAllowedIntensityRatioToBasePeak = 0.01
NormalizePeaksAccrossAllWindows = false
TrimMs1Peaks = false
TrimMsMsPeaks = true
UseDeltaScore = false
CustomIons = []
AssumeOrphanPeaksAreZ1Fragments = true
MaxHeterozygousVariants = 4
MinVariantDepth = 1
AddTruncations = false
DissociationType = "HCD"
SeparationType = "HPLC"
MS2ChildScanDissociationType = "Unknown"
MS3ChildScanDissociationType = "Unknown"

[CommonParameters.DigestionParams]
MaxMissedCleavages = 3
InitiatorMethionineBehavior = "Variable"
MinPeptideLength = 5
MaxPeptideLength = 60
MaxModificationIsoforms = 1024
MaxModsForPeptide = 2
Protease = "trypsin"
SearchModeType = "Full"
FragmentationTerminus = "Both"
SpecificProtease = "trypsin"
GeneratehUnlabeledProteinsForSilac = true
KeepNGlycopeptide = false
KeepOGlycopeptide = false
```
System OS: Windows 11
MetaMorpheus Version: 1.0.5
Available RAM: 768 GB
CPU: EPYC 9754 128c/256t

Are there other dumps/logs I should attach?

**Comment by acesnik** [comment]
🤖 Thanks for the report — this one is found and fixed, in mzLib rather than here: smith-chem-wisc/mzLib#1184.

It isn't specific to crosslink search. The crash is in the MGF reader, during file loading, before any search work starts, so the same file would have failed the same way in a plain Search task. The title and the `XLSearchTask` frame in the stack both point at the crosslink code, which is misleading — `MyFileManager.LoadFile` is shared by every task.

The reader had four places that read a value off a line without checking one was present: a peak line with an m/z but no intensity, and `PEPMASS`, `CHARGE` or `SCANS` written without an `=` or with nothing after it. Any of those threw `Index was outside the bounds of the array` and took the whole file down, rather than the line being skipped — which is what the reader already does with other unrecognised content. Now they skip.

Two caveats. Your file isn't attached, so I can't say which of the four cases it hit; all four produced the exception you saw, and all four are fixed. And because the fix is in mzLib, it reaches MetaMorpheus only after an mzLib release and a dependency bump here, so it won't be in a build immediately.

If you still have that MGF, a dozen lines from around one of the scans would let me confirm the specific case — but it isn't needed for the fix.
