### ISSUE TITLE
Metamorpheous Crashed While Doing GPTMD and GlycoSearch

### ISSUE THREAD

**Issue by naviyas** [smith-chem-wisc/MetaMorpheus#2422]
**Describing the issue**
 MetaMorpheus crashed during task 3, the GlycoSearch task. I was trying to run a series of tasks including: calibrate, GPTMD, GlycoSearch, and finally a search. 

**Reproducing the error**

- Protein database
 uniprotkb_proteome_UP000005640_AND_revi_2024_10_04
Contaminants\MetaMorpheusContaminants.xml Downloaded on: 09/16/2024 19:14:14

- Mass spectrometry file types
 Thermo QE .raw files
There were a total of 9 raw files 3 bio reps with each having 3 tech reps

- Settings

For Task 1 - Calibrate: The following calibration settings were used: protease = trypsin; maximum missed cleavages = 2; minimum peptide length = 7; maximum peptide length = unspecified; initiator methionine behavior = Variable; fixed modifications = Carbamidomethyl on C, Carbamidomethyl on U; variable modifications = Oxidation on M; max mods per peptide = 2; max modification isoforms = 1024; precursor mass tolerance = ±15.0000 PPM; product mass tolerance = ±3.0000 Absolute. The combined search database contained 20676 non-decoy protein entries including 528 contaminant sequences.

For Task 2 - GPTMD: The following G-PTM-D settings were used: protease = trypsin; maximum missed cleavages = 2; minimum peptide length = 7; maximum peptide length = unspecified; initiator methionine behavior = Variable; max modification isoforms = 1024; fixed modifications = Carbamidomethyl on C, Carbamidomethyl on U; variable modifications = Oxidation on M; G-PTM-D modifications count = 87; precursor mass tolerance(s) = {±10.0000 PPM around -18.010564684, -17.026549101, -16.042533, -2.015649999999999, -1.0316339999999986, 0, 0.984015583, 1.968032, 4.955394000000002, 14.015650064, 14.999666000000001, 15.99491462, 16.978931, 21.969391633, 21.98194425, 22.965959, 27.99491462, 28.031300129, 28.990163592, 31.98983, 37.946940799, 37.955881454, 37.976858, 42.010564684, 42.046950193, 42.994581, 43.005813656, 43.963886, 43.989829239, 44.985078211, 52.911461233, 53.919286266, 61.913491946, 61.921772688, 63.992508, 68.026214748, 70.041864813, 79.956815033, 79.966330889, 86.000393923, 86.036779433, 100.016043988, 101.948274, 114.031694052, 146.057908801, 159.932662, 162.05282342, 176.032087975, 203.079372521, 229.014009359, 349.137281322, 365.132195941, 406.158745043, 541.06110975, 672.22252707, 730.264391883, 876.322300683, 947.323028959, 963.317943579, 1038.375124104, 1216.422862143 Da}; product mass tolerance = ±0.2000 Absolute. The combined search database contained 20676 non-decoy protein entries including 528 contaminant sequences.

For Task 3 - GlycoSearch: MetaMorpheus: version 1.0.6
Data files were processed on a computer running Microsoft Windows 10.0.22631 with a 64-bit Intel(R) Xeon(R) Silver 4215 CPU @ 2.50GHz processor with 16 threads and 64GB installed RAM.
.NET version: .NET 8.0.8
e: System.AggregateException: One or more errors occurred. (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.) (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.) (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.) (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.) (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.) (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.) (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.) (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.) (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.) (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.) (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.) (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.)
 ---> System.InvalidCastException: Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.
   at EngineLayer.ProteinParsimonyEngine.<>c__DisplayClass7_1.<RunProteinParsimonyEngine>b__2(Tuple`2 range, ParallelLoopState loopState) in C:\projects\metamorpheus\MetaMorpheus\EngineLayer\ProteinParsimony\ProteinParsimonyEngine.cs:line 186
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](Partitioner`1 source, ParallelOptions parallelOptions, Action`2 body)
   at EngineLayer.ProteinParsimonyEngine.RunProteinParsimonyEngine() in C:\projects\metamorpheus\MetaMorpheus\EngineLayer\ProteinParsimony\ProteinParsimonyEngine.cs:line 119
   at EngineLayer.ProteinParsimonyEngine.RunSpecific() in C:\projects\metamorpheus\MetaMorpheus\EngineLayer\ProteinParsimony\ProteinParsimonyEngine.cs:line 70
   at EngineLayer.MetaMorpheusEngine.Run() in C:\projects\metamorpheus\MetaMorpheus\EngineLayer\MetaMorpheusEngine.cs:line 282
   at TaskLayer.PostGlycoSearchAnalysisTask.GlycoProteinAnalysis(List`1 gsms, String outputFolder, String individualFileFolder, MyTaskResults myTaskResults) in C:\projects\metamorpheus\MetaMorpheus\TaskLayer\GlycoSearchTask\PostGlycoSearchAnalysisTask.cs:line 294
   at TaskLayer.PostGlycoSearchAnalysisTask.Run(String OutputFolder, List`1 dbFilenameList, List`1 currentRawFileList, String taskId, FileSpecificParameters[] fileSettingsList, List`1 allPsms, CommonParameters commonParameters, GlycoSearchParameters glycoSearchParameters, List`1 proteinList, List`1 variableModifications, List`1 fixedModifications, List`1 localizeableModificationTypes, MyTaskResults MyTaskResults) in C:\projects\metamorpheus\MetaMorpheus\TaskLayer\GlycoSearchTask\PostGlycoSearchAnalysisTask.cs:line 149
   at TaskLayer.GlycoSearchTask.RunSpecific(String OutputFolder, List`1 dbFilenameList, List`1 currentRawFileList, String taskId, FileSpecificParameters[] fileSettingsList) in C:\projects\metamorpheus\MetaMorpheus\TaskLayer\GlycoSearchTask\GlycoSearchTask.cs:line 227
   at TaskLayer.MetaMorpheusTask.RunTask(String output_folder, List`1 currentProteinDbFilenameList, List`1 currentRawDataFilepathList, String displayName) in C:\projects\metamorpheus\MetaMorpheus\TaskLayer\MetaMorpheusTask.cs:line 539
 ---> (Inner Exception #1) System.InvalidCastException: Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.
   at EngineLayer.ProteinParsimonyEngine.<>c__DisplayClass7_1.<RunProteinParsimonyEngine>b__2(Tuple`2 range, ParallelLoopState loopState) in C:\projects\metamorpheus\MetaMorpheus\EngineLayer\ProteinParsimony\ProteinParsimonyEngine.cs:line 186
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #2) System.InvalidCastException: Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.
   at EngineLayer.ProteinParsimonyEngine.<>c__DisplayClass7_1.<RunProteinParsimonyEngine>b__2(Tuple`2 range, ParallelLoopState loopState) in C:\projects\metamorpheus\MetaMorpheus\EngineLayer\ProteinParsimony\ProteinParsimonyEngine.cs:line 186
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #3) System.InvalidCastException: Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.
   at EngineLayer.ProteinParsimonyEngine.<>c__DisplayClass7_1.<RunProteinParsimonyEngine>b__2(Tuple`2 range, ParallelLoopState loopState) in C:\projects\metamorpheus\MetaMorpheus\EngineLayer\ProteinParsimony\ProteinParsimonyEngine.cs:line 186
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #4) System.InvalidCastException: Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.
   at EngineLayer.ProteinParsimonyEngine.<>c__DisplayClass7_1.<RunProteinParsimonyEngine>b__2(Tuple`2 range, ParallelLoopState loopState) in C:\projects\metamorpheus\MetaMorpheus\EngineLayer\ProteinParsimony\ProteinParsimonyEngine.cs:line 186
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #5) System.InvalidCastException: Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.
   at EngineLayer.ProteinParsimonyEngine.<>c__DisplayClass7_1.<RunProteinParsimonyEngine>b__2(Tuple`2 range, ParallelLoopState loopState) in C:\projects\metamorpheus\MetaMorpheus\EngineLayer\ProteinParsimony\ProteinParsimonyEngine.cs:line 186
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #6) System.InvalidCastException: Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.
   at EngineLayer.ProteinParsimonyEngine.<>c__DisplayClass7_1.<RunProteinParsimonyEngine>b__2(Tuple`2 range, ParallelLoopState loopState) in C:\projects\metamorpheus\MetaMorpheus\EngineLayer\ProteinParsimony\ProteinParsimonyEngine.cs:line 186
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #7) System.InvalidCastException: Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.
   at EngineLayer.ProteinParsimonyEngine.<>c__DisplayClass7_1.<RunProteinParsimonyEngine>b__2(Tuple`2 range, ParallelLoopState loopState) in C:\projects\metamorpheus\MetaMorpheus\EngineLayer\ProteinParsimony\ProteinParsimonyEngine.cs:line 186
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #8) System.InvalidCastException: Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.
   at EngineLayer.ProteinParsimonyEngine.<>c__DisplayClass7_1.<RunProteinParsimonyEngine>b__2(Tuple`2 range, ParallelLoopState loopState) in C:\projects\metamorpheus\MetaMorpheus\EngineLayer\ProteinParsimony\ProteinParsimonyEngine.cs:line 186
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #9) System.InvalidCastException: Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.
   at EngineLayer.ProteinParsimonyEngine.<>c__DisplayClass7_1.<RunProteinParsimonyEngine>b__2(Tuple`2 range, ParallelLoopState loopState) in C:\projects\metamorpheus\MetaMorpheus\EngineLayer\ProteinParsimony\ProteinParsimonyEngine.cs:line 186
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #10) System.InvalidCastException: Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.
   at EngineLayer.ProteinParsimonyEngine.<>c__DisplayClass7_1.<RunProteinParsimonyEngine>b__2(Tuple`2 range, ParallelLoopState loopState) in C:\projects\metamorpheus\MetaMorpheus\EngineLayer\ProteinParsimony\ProteinParsimonyEngine.cs:line 186
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #11) System.InvalidCastException: Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.
   at EngineLayer.ProteinParsimonyEngine.<>c__DisplayClass7_1.<RunProteinParsimonyEngine>b__2(Tuple`2 range, ParallelLoopState loopState) in C:\projects\metamorpheus\MetaMorpheus\EngineLayer\ProteinParsimony\ProteinParsimonyEngine.cs:line 186
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---
e.Message: One or more errors occurred. (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.) (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.) (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.) (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.) (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.) (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.) (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.) (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.) (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.) (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.) (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.) (Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.)e.InnerException: System.InvalidCastException: Unable to cast object of type 'EngineLayer.GlycoSearch.GlycoSpectralMatch' to type 'EngineLayer.PeptideSpectralMatch'.
   at EngineLayer.ProteinParsimonyEngine.<>c__DisplayClass7_1.<RunProteinParsimonyEngine>b__2(Tuple`2 range, ParallelLoopState loopState) in C:\projects\metamorpheus\MetaMorpheus\EngineLayer\ProteinParsimony\ProteinParsimonyEngine.cs:line 186
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass43_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()e.Source: System.Threading.Tasks.Parallele.StackTrace:    at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](Partitioner`1 source, ParallelOptions parallelOptions, Action`2 body)
   at EngineLayer.ProteinParsimonyEngine.RunProteinParsimonyEngine() in C:\projects\metamorpheus\MetaMorpheus\EngineLayer\ProteinParsimony\ProteinParsimonyEngine.cs:line 119
   at EngineLayer.ProteinParsimonyEngine.RunSpecific() in C:\projects\metamorpheus\MetaMorpheus\EngineLayer\ProteinParsimony\ProteinParsimonyEngine.cs:line 70
   at EngineLayer.MetaMorpheusEngine.Run() in C:\projects\metamorpheus\MetaMorpheus\EngineLayer\MetaMorpheusEngine.cs:line 282
   at TaskLayer.PostGlycoSearchAnalysisTask.GlycoProteinAnalysis(List`1 gsms, String outputFolder, String individualFileFolder, MyTaskResults myTaskResults) in C:\projects\metamorpheus\MetaMorpheus\TaskLayer\GlycoSearchTask\PostGlycoSearchAnalysisTask.cs:line 294
   at TaskLayer.PostGlycoSearchAnalysisTask.Run(String OutputFolder, List`1 dbFilenameList, List`1 currentRawFileList, String taskId, FileSpecificParameters[] fileSettingsList, List`1 allPsms, CommonParameters commonParameters, GlycoSearchParameters glycoSearchParameters, List`1 proteinList, List`1 variableModifications, List`1 fixedModifications, List`1 localizeableModificationTypes, MyTaskResults MyTaskResults) in C:\projects\metamorpheus\MetaMorpheus\TaskLayer\GlycoSearchTask\PostGlycoSearchAnalysisTask.cs:line 149
   at TaskLayer.GlycoSearchTask.RunSpecific(String OutputFolder, List`1 dbFilenameList, List`1 currentRawFileList, String taskId, FileSpecificParameters[] fileSettingsList) in C:\projects\metamorpheus\MetaMorpheus\TaskLayer\GlycoSearchTask\GlycoSearchTask.cs:line 227
   at TaskLayer.MetaMorpheusTask.RunTask(String output_folder, List`1 currentProteinDbFilenameList, List`1 currentRawDataFilepathList, String displayName) in C:\projects\metamorpheus\MetaMorpheus\TaskLayer\MetaMorpheusTask.cs:line 539e.TargetSite: Void Run[TState](ReplicatableUserAction`1, System.Threading.Tasks.ParallelOptions, Boolean)

Task 4 - Search Task: The default search task, but I changed precursor to 10 ppm and fragment to 0.2 Da. All other defaults were left on. 

- Example datafiles

I put the data files on my folder on Bison. They are in the folder "Metamorpheous Failed Samples"
I've also included the results from the search and the database I used. 

**Expected behavior for GUI**

**Screenshots**

**Desktop information**
Data files were processed on a computer running Microsoft Windows 10.0.22631 with a 64-bit Intel(R) Xeon(R) Silver 4215 CPU @ 2.50GHz processor with 16 threads and 64GB installed RAM. 

**Additional context**

**Comment by acesnik** [comment]
🤖 Fixed in #2514, released in 1.1.0 (2025-06-20). You were on 1.0.6, which predates it.

The crash was `ProteinParsimonyEngine.cs:186`, which read `foreach (PeptideSpectralMatch psm in baseSequence.Value)`. That collection is a `List<SpectralMatch>`, and naming an explicit element type in a `foreach` inserts a cast on every element — so a `GlycoSpectralMatch` threw `InvalidCastException`, once per parallel worker, which is the `AggregateException` you saw. `GlycoSpectralMatch` and `PeptideSpectralMatch` are siblings under the abstract `SpectralMatch`, so the cast could never succeed on a glyco search; a regular search feeds the same code `PeptideSpectralMatch` and is unaffected, which is why this only showed up in the GlycoSearch task.

#2340 had already generalised the engine's list types to `SpectralMatch` in March 2024 and just missed this line; #2514 changed it to `foreach (SpectralMatch psm in ...)`. On current master `PostGlycoSearchAnalysisTask` upcasts to `SpectralMatch` before calling the engine, and the engine has no `PeptideSpectralMatch` reference left.

Closing on the code rather than on a reproduction — I haven't re-run your files. If you hit this on 1.1.0 or later, please reopen with the new `prose.txt` and it'd be a different bug.
