### ISSUE TITLE
The path is not of a legal form

### ISSUE THREAD

**Issue by tiagosobreira** [smith-chem-wisc/MetaMorpheus#471]
I am trying to run MM with two mzML files and It gives this error:

0.0.119.0
-t , SearchTaskconfig.toml , -s , 5_Calibrated.mzML , 6_Calibrated.mzML , -d , Task1Gptmd\uniprot-Arabidopsis+thalianaGPTMD.xml
 
Unhandled Exception: System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPath
Length, Boolean expandShortPaths)
   at System.IO.Path.GetDirectoryName(String path)
   at TaskLayer.EverythingRunnerEngine.Run() in C:\projects\metamorpheus\TaskLayer\EverythingRunner\EverythingRunnerEngine.cs:line 68
   at MetaMorpheusCommandLine.Program.Main(String[] args) in C:\projects\metamorpheus\CMD\Program.cs:line 105

The command line that I used was:

MetaMorpheusCommandLine.exe -t SearchTaskconfig.toml -s 5_Calibrated.mzML 6_Calibrated.mzML -d uniprot-Arabidopsis+thalianaGPTMD.xml

If I run using just one file, It works fine.

Thank you,
Tiago

**Comment by stefanks** [comment]
Could you try running it with quotation marks around the file names?

**Comment by stefanks** [comment]
Also, could you try removing the _ and + characters from the file names? 
Thanks!

**Comment by stefanks** [comment]
Fixed in https://github.com/smith-chem-wisc/MetaMorpheus/pull/483

Please try again!
